debug: false

menu:
  select-more:
    menu: buy-more
    max-amount: 64
  auto-open:
    enabled: true
    menu: main
  click-event:
    buy: 'SHIFT_LEFT'
    sell: 'RIGHT'
    buy-or-sell: 'LEFT'
    select-amount: 'SHIFT_RIGHT'
    sell-all: 'DROP'

use-times:
  default-reset-mode: 'NEVER'
  default-reset-time: '00:00:00'

# TODO
dynamic-prices:
  default-enabled: false
  default-add-amount: 5
  default-remove-amount: 4

check-math: false

send-messages-after-buy: true

display-item:
  auto-set-first-product: true
  add-displayname: ' x{amount}'
  add-lore:
    top:
      - ''
    buy-price:
      - '&ePurchase: {buy-price}'
    sell-price:
      - '&eSell: {sell-price}'
    buy-limit-player:
      - '&#FF7777Player Buy Stock: {buy-times-player}/{buy-limit-player}'
    buy-limit-server:
      - '&#FF7777Server Buy Stock: {buy-times-server}/{buy-limit-server}'
    sell-limit-player:
      - '&#FF7777Player Sell Limit: {sell-times-player}/{sell-limit-player}'
    sell-limit-server:
      - '&#FF7777Server Sell Limit: {sell-times-server}/{sell-limit-server}'
    buy-refresh-player:
      - ''
      - '&#ff3300cCan not buy more!'
      - '&8Refresh Time: {buy-refresh-player}'
    buy-refresh-server:
      - ''
      - '&#ff3300Sold Out!'
      - '&8Refresh Time: {buy-refresh-server}'
    sell-refresh-player:
      - ''
      - '&#ff3300Can not sell more!'
      - '&8Refresh Time: {sell-refresh-player}'
    sell-refresh-server:
      - ''
      - '&#ff3300Can not sell more for server!'
      - '&8Refresh Time: {sell-refresh-server}'
    buy-click:
      - '{buy-click}'
    sell-click:
      - '{sell-click}'
    below:
      - '&#FFFACDRight-Shift click to pick amount!'
      - '&#FFFACDDrop (Q key) to sell all!'

placeholder:
  refresh:
    format: "yyyy-MM-dd HH:mm:ss"
    never: "Never"
  price:
    split-symbol-any: ' or '
    split-symbol-all: ', '
    unknown: "Unknown"
    unknown-price-type: "Unknown Price Type"
  click:
    enabled: true
    buy: '&#FFFACDLeft-click to buy!'
    sell: '&#FFFACDRight-click to sell!'
    buy-with-no-sell: '&#FFFACDClick to buy!'
    sell-with-no-buy: '&#FFFACDClick to sell!'
    buy-max-limit-player: '&#ff3300You can not buy more!'
    buy-max-limit-server: '&#ff3300SOLD OUT!'
    sell-max-limit-player: '&#ff3300Can not sell more!'
    sell-max-limit-server: '&#ff3300THIS ITEM CAN NOT BE SELLED!'
    buy-price-not-enough: '&#ff3300Do not have enough money to buy!'
    sell-price-not-enough: '&#ff3300Do not have enough item to sell!'
    error: '&#ff3300Error!'

database:
  enabled: false
  jdbc-url: "jdbc:mysql://localhost:3306/ultimateshop?useSSL=false&autoReconnect=true"
  jdbc-class: "com.mysql.cj.jdbc.Driver"
  properties:
    user: root
    password: 123456

prices:
  example:
    economy-plugin: Vault
    amount: 200
    placeholder: '200 Coins'
  mmoitems-example:
    hook-plugin: MMOItems
    hook-item: AXE;;TEST_AXE
    amount: 1
    placeholder: '1 Mythic Axe'