debug: true

menu:
  select-more:
    menu: buy-more
    max-amount: 64
  auto-open:
    enabled: true
    menu: main
  click-event:
    buy: 'LEFT'
    sell: 'RIGHT'
    select-amount: 'SHIFT_RIGHT'

use-times:
  default-reset-mode: 'NEVER'
  default-reset-time: '00:00:00'

# TODO
dynamic-prices:
  default-enabled: false
  default-add-amount: 5
  default-remove-amount: 4

check-math: false

display-item:
  auto-set-first-product: true
  add-displayname: ' x{amount}'
  add-lore:
    top:
      - ''
    buy-price:
      - '&7Purchase: {buy-price}'
    sell-price:
      - '&7Sell: {sell-price}'
    buy-limit:
      - '&7Player Buy Stock: {buy-times-player}/{buy-limit-player}'
      - '&7Server Buy Stock: {buy-times-server}/{buy-limit-server}'
    sell-limit:
      - '&7Player Sell Limit: {sell-times-player}/{sell-limit-player}'
      - '&7Server Sell Limit: {sell-times-server}/{sell-limit-server}'
    buy-refresh-player:
      - ''
      - '&cCan not buy more!'
      - '&8Refresh Time: {buy-refresh-player}'
    buy-refresh-server:
      - ''
      - '&cSold Out!'
      - '&8Refresh Time: {buy-refresh-server}'
    sell-refresh-player:
      - ''
      - '&cCan not sell more!'
      - '&8Refresh Time: {sell-refresh-player}'
    sell-refresh-server:
      - ''
      - '&cCan not sell more for server!'
      - '&8Refresh Time: {sell-refresh-server}'
    buy-click:
      - '{buy-click}'
    sell-click:
      - '{sell-click}'
    below:
      - '&eRight-Shift click to pick amount!'

placeholder:
  refresh:
    format: "yyyy-MM-dd HH:mm:ss"
    never: "Never"
  price:
    split-symbol-any: ' or '
    split-symbol-all: ', '
    unknown: "Unknown"
  click:
    enabled: true
    buy: '&eLeft-click to buy!'
    sell: '&eRight-click to sell!'
    buy-max-limit-player: '&cYou can not buy more!'
    buy-max-limit-server: '&cSOLD OUT!'
    sell-max-limit-player: '&cCan not sell more!'
    sell-max-limit-server: '&cTHIS ITEM CAN NOT BE SELLED!'
    buy-price-not-enough: '&cDo not have enough money to buy!'
    sell-price-not-enough: '&cDo not have enough item to sell!'
    error: '&cError!'

database:
  enabled: false
  jdbc-url: "jdbc:mysql://localhost:3306/ultimateshop?useSSL=false&autoReconnect=true"
  jdbc-class: "com.mysql.cj.jdbc.Driver"
  properties:
    user: root
    password: 123456

prices:
  example:
    economy-plugin: Vault
    amount: 200
    placeholder: '200 Coins'
  mmoitems-example:
    hook-plugin: MMOItems
    hook-item: AXE;;TEST_AXE
    amount: 1
    placeholder: '1 Mythic Axe'