name: UltimateShop
version: '${project.version}'
main: cn.superiormc.ultimateshop.UltimateShop
api-version: 1.14
author:
  - PQguanfang
  - rzt1020
softdepend:
  - MMOItems
  - MythicLib
  - ItemsAdder
  - Vault
  - PlayerPoints
  - GamePoints
  - Oraxen
  - EcoItems
  - EcoArmor
  - PlaceholderAPI
  - UltraEconomy
  - CoinsEngine
  - RedisEconomy
  - EcoBits
  - MythicMobs
  - PEconomy
  - RoyaleEconomy
  - AdvancedEnchantments
  - NeigeItems
  - floodgate
commands:
  ultimateshop:
    aliases:
      - "shop"
    usage: "/ultimateshop"
    description: "UltimateShop Main Command."